"""empty message

Revision ID: 05404c86fa7f
Revises: 
Create Date: 2019-04-03 11:01:55.779973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05404c86fa7f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lot_location'), 'lot', ['location'], unique=False)
    op.create_table('calculation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_spots', sa.Integer(), nullable=True),
    sa.Column('available_spots', sa.Integer(), nullable=True),
    sa.Column('percentage', sa.Integer(), nullable=True),
    sa.Column('lot_location', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['lot_location'], ['lot.location'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calculation_available_spots'), 'calculation', ['available_spots'], unique=False)
    op.create_index(op.f('ix_calculation_percentage'), 'calculation', ['percentage'], unique=False)
    op.create_index(op.f('ix_calculation_total_spots'), 'calculation', ['total_spots'], unique=False)
    op.create_table('frame',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('frame_fname', sa.String(length=64), nullable=True),
    sa.Column('video_fname', sa.String(length=64), nullable=True),
    sa.Column('lot_location', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['lot_location'], ['lot.location'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_frame_frame_fname'), 'frame', ['frame_fname'], unique=False)
    op.create_index(op.f('ix_frame_video_fname'), 'frame', ['video_fname'], unique=False)
    op.create_table('spot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spot_id', sa.Integer(), nullable=True),
    sa.Column('availability', sa.Boolean(create_constraint=140), nullable=True),
    sa.Column('lot_location', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['lot_location'], ['lot.location'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spot_availability'), 'spot', ['availability'], unique=False)
    op.create_index(op.f('ix_spot_spot_id'), 'spot', ['spot_id'], unique=False)
    op.create_table('yaml',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('yaml_fname', sa.String(length=64), nullable=True),
    sa.Column('lot_location', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['lot_location'], ['lot.location'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_yaml_yaml_fname'), 'yaml', ['yaml_fname'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_yaml_yaml_fname'), table_name='yaml')
    op.drop_table('yaml')
    op.drop_index(op.f('ix_spot_spot_id'), table_name='spot')
    op.drop_index(op.f('ix_spot_availability'), table_name='spot')
    op.drop_table('spot')
    op.drop_index(op.f('ix_frame_video_fname'), table_name='frame')
    op.drop_index(op.f('ix_frame_frame_fname'), table_name='frame')
    op.drop_table('frame')
    op.drop_index(op.f('ix_calculation_total_spots'), table_name='calculation')
    op.drop_index(op.f('ix_calculation_percentage'), table_name='calculation')
    op.drop_index(op.f('ix_calculation_available_spots'), table_name='calculation')
    op.drop_table('calculation')
    op.drop_index(op.f('ix_lot_location'), table_name='lot')
    op.drop_table('lot')
    # ### end Alembic commands ###
