"""empty message

Revision ID: 1739dbf4b1aa
Revises: 
Create Date: 2019-03-01 15:29:38.186700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1739dbf4b1aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lot_location'), 'lot', ['location'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lot_location'), table_name='lot')
    op.drop_table('lot')
    # ### end Alembic commands ###
