- id: 0
  lot: 2
  points:
  - - 46
    - 158
  - - 101
    - 158
  - - 46
    - 278
  - - 101
    - 278
- id: 0
  lot: 2
  points:
  - - 114
    - 156
  - - 181
    - 156
  - - 114
    - 272
  - - 181
    - 272
- id: 0
  lot: 2
  points:
  - - 190
    - 158
  - - 258
    - 158
  - - 190
    - 273
  - - 258
    - 273
- id: 0
  lot: 2
  points:
  - - 269
    - 162
  - - 326
    - 162
  - - 269
    - 272
  - - 326
    - 272
- id: 0
  lot: 2
  points:
  - - 339
    - 161
  - - 399
    - 161
  - - 339
    - 270
  - - 399
    - 270
- id: 0
  lot: 2
  points:
  - - 39
    - 293
  - - 94
    - 293
  - - 39
    - 416
  - - 94
    - 416
- id: 0
  lot: 2
  points:
  - - 112
    - 288
  - - 167
    - 288
  - - 112
    - 409
  - - 167
    - 409
- id: 0
  lot: 2
  points:
  - - 191
    - 287
  - - 255
    - 287
  - - 191
    - 405
  - - 255
    - 405
- id: 0
  lot: 2
  points:
  - - 270
    - 287
  - - 324
    - 287
  - - 270
    - 403
  - - 324
    - 403
- id: 0
  lot: 2
  points:
  - - 337
    - 284
  - - 402
    - 284
  - - 337
    - 402
  - - 402
    - 402
