- id: 1
  lot: 1
  points:
  - - 206
    - 220
  - - 293
    - 220
  - - 293
    - 33
  - - 206
    - 33
- id: 2
  lot: 1
  points:
  - - 53
    - 194
  - - 155
    - 194
  - - 155
    - 38
  - - 53
    - 38
