- id: 0
  lot: 1
  points:
  - - 16
    - 48
  - - 144
    - 48
  - - 16
    - 258
  - - 144
    - 258
- id: 0
  lot: 1
  points:
  - - 163
    - 48
  - - 266
    - 48
  - - 163
    - 265
  - - 266
    - 265
- id: 0
  lot: 1
  points:
  - - 290
    - 40
  - - 397
    - 40
  - - 290
    - 262
  - - 397
    - 262
- id: 0
  lot: 1
  points:
  - - 437
    - 35
  - - 517
    - 35
  - - 437
    - 261
  - - 517
    - 261
- id: 0
  lot: 1
  points:
  - - 553
    - 34
  - - 629
    - 34
  - - 553
    - 257
  - - 629
    - 257
- id: 0
  lot: 1
  points:
  - - 25
    - 294
  - - 146
    - 294
  - - 25
    - 465
  - - 146
    - 465
- id: 0
  lot: 1
  points:
  - - 168
    - 281
  - - 266
    - 281
  - - 168
    - 471
  - - 266
    - 471
- id: 0
  lot: 1
  points:
  - - 288
    - 285
  - - 404
    - 285
  - - 288
    - 472
  - - 404
    - 472
- id: 0
  lot: 1
  points:
  - - 415
    - 282
  - - 517
    - 282
  - - 415
    - 471
  - - 517
    - 471
- id: 0
  lot: 1
  points:
  - - 534
    - 282
  - - 635
    - 282
  - - 534
    - 473
  - - 635
    - 473
