- id: 0
  lot: 1
  points:
  - - 84
    - 118
  - - 108
    - 118
  - - 84
    - 157
  - - 108
    - 157
- id: 0
  lot: 1
  points:
  - - 119
    - 113
  - - 138
    - 113
  - - 119
    - 149
  - - 138
    - 149
- id: 0
  lot: 1
  points:
  - - 146
    - 113
  - - 170
    - 113
  - - 146
    - 145
  - - 170
    - 145
- id: 0
  lot: 1
  points:
  - - 180
    - 110
  - - 199
    - 110
  - - 180
    - 142
  - - 199
    - 142
- id: 0
  lot: 1
  points:
  - - 205
    - 106
  - - 228
    - 106
  - - 205
    - 139
  - - 228
    - 139
- id: 0
  lot: 1
  points:
  - - 82
    - 171
  - - 103
    - 171
  - - 82
    - 205
  - - 103
    - 205
- id: 0
  lot: 1
  points:
  - - 118
    - 163
  - - 134
    - 163
  - - 118
    - 199
  - - 134
    - 199
- id: 0
  lot: 1
  points:
  - - 145
    - 157
  - - 172
    - 157
  - - 145
    - 198
  - - 172
    - 198
- id: 0
  lot: 1
  points:
  - - 181
    - 156
  - - 200
    - 156
  - - 181
    - 192
  - - 200
    - 192
- id: 0
  lot: 1
  points:
  - - 207
    - 152
  - - 230
    - 152
  - - 207
    - 190
  - - 230
    - 190
