- id: 3
  lot: 2
  points:
  - - 32
    - 215
  - - 99
    - 215
  - - 99
    - 64
  - - 32
    - 64
- id: 4
  lot: 2
  points:
  - - 134
    - 224
  - - 199
    - 224
  - - 199
    - 74
  - - 134
    - 74
- id: 5
  lot: 2
  points:
  - - 241
    - 207
  - - 298
    - 207
  - - 298
    - 81
  - - 241
    - 81
